## Problem
> There are many seasons that sales are significantly higher or lower than averages. If the company does not know about these seasons, it can lose too much money. Predicting future sales is one of the most crucial plans for a company. Sales forecasting gives an idea to the company for arranging stocks, calculating revenue, and deciding to make a new investment. Another advantage of knowing future sales is that achieving predetermined targets from the beginning of the seasons can have a positive effect on stock prices and investors' perceptions. Also, not reaching the projected target could significantly damage stock prices, conversely. And, it will be a big problem especially for Walmart as a big company.

## Aim
> My aim in this project is to build a model which predicts sales of the stores. With this model, Walmart authorities can decide their future plans which is very important for arranging stocks, calculating revenue and deciding to make new investment or not.

## Step

In [2]:
import logging
import warnings
import pandas as pd
import numpy as np
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import category_encoders as ce
from lightgbm import LGBMRegressor
from sklearn.model_selection import train_test_split, RandomizedSearchCV
import shap
from sklearn.metrics import r2_score
#import check_numeric

sns.set_style('darkgrid')
sns.set_palette("bright")
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
%config InlineBackend.figure_format = 'retina'
%matplotlib inline

In [71]:
class SalesPredict:

    """
    store 별 판매량 예측
     > trainset: 2010-02-05 ~ 2012-10-26
     > testset: 2012-11-02 ~ 2013-07-26
    """
    
    def __init__(self):
        self.file_path = "data"        
        self.datasets = ['features', 'stores', 'train', 'test']
        self.loaded_datasets = {}
        self.label_encoder = LabelEncoder()
        self.target_encoder = ce.TargetEncoder(cols=['warehouse'])        
        self.base_model = LGBMRegressor()
        self.use_vote_regressor = False
        self.opt_param = False # True 경우 파라메터 최적화 진행
        self.param_space = {
                            'learning_rate': np.logspace(-3, 0, num=100),
                            'n_estimators': np.arange(50, 300, step=10),
                            'max_depth': np.arange(3, 11),
                            'num_leaves': np.arange(10, 101),
                            'min_child_samples': np.arange(5, 31)
                            } 
        
        
    def load_data(self):
        """
        데이터셋 불러오기
        분리된 데이터셋을 병합
        """
        for data in self.datasets:
            df = pd.read_csv(f"{self.file_path}/{data}.csv") 
            df.columns = df.columns.str.lower()
            self.loaded_datasets[data] = df
        
        # 각각 df 불러오기
        features = self.loaded_datasets['features']
        stores = self.loaded_datasets['stores']
        train = self.loaded_datasets['train']
        test = self.loaded_datasets['test']
                
        # 병합
        df = pd.concat([train, test])        
        df = df.merge(features, on=['store','date','isholiday'], how='left')\
                     .merge(stores, on=['store'], how='left')
        
        # columns type change
        df['date'] = pd.to_datetime(df['date'])
        df['isholiday'] = df['isholiday'].astype(int)
        #df['is_test'] = np.where(df['weekly_sales'].isnull() == True, 1, 0)        
        
        # shape check
        assert len(df) == len(train)+len(test)
        print(df.shape)
        return df
    
    
    def add_date_features(self, df):
        
        """
        날짜 관련 피처엔지니어링
        """
        df['month'] = df['date'].dt.month
        #df['day'] = df['date'].dt.dayofweek
        #df['dayofweek'] = df['date'].dt.day_name()
        #df["weekend_yn"] = np.where(df["dayofweek"].isin(["Saturday", "Sunday"]), 1, 0)  # 주말여부
        df["dayofyear"] = df['date'].dt.dayofyear  # 연간 일                
        df["week_no"] = df['date'].dt.isocalendar()['week'].astype('int')
        df['week_num'] = np.ceil((df['date'].dt.to_period('M').dt.to_timestamp().dt.weekday + df['date'].dt.day) / 7.0).astype(int)  # 월별주차
        #df = pd.concat([df, pd.get_dummies(data=df['dayofweek'], prefix='dayofweek')], axis=1)  # 요일 one-hot encoding

        # 월별 누적주문수
        # monthly prediction을 위해 YYYY-MM 형태로 변환
        # df['date_month'] = pd.to_datetime(df['target_date'].dt.strftime('%Y-%m'))        
        # df['ord_cnt_cum'] = df.groupby(['date_month', 'warehouse'])['order'].cumsum()        
        return df
    
    
    def add_fe_laggging(self, df, max_lagging_n=30):
        pass
    
    
    
    def fit_predict(self, df):
        
        # index target_date로 지정
        if 'date' in df.columns:
            df = df.set_index("date")             
            
        # [중요] 컬럼제거: 에러 및 leakage 방지
        drop_cols = ['weekly_sales']
        df = df.drop(drop_cols, axis=1).dropna(subset=['weekly_sales'])

        pred_res = pd.DataFrame()
        for date in pd.period_range('2012-01-01', '2012-10-26'):            
            print("train and predict of", date)            
            train = df[df.index < str(date)]
            pred = df[df.index == str(date)]
            
            train['type'] = self.label_encoder.fit_transform(train['type'])
            train['store_enc'] = self.target_encoder.fit_transform(train['store'], train['weekly_sales'])
            train['dept_enc'] = self.target_encoder.fit_transform(train['dept'], train['weekly_sales'])
            X_train = train.drop("weekly_sales", axis=1)
            y_train = train[['weekly_sales']]

            # 성능 체크 용도
            # label_encoder? self?
            pred['type'] = self.label_encoder.transform(pred['type'])
            pred['store_enc'] = self.target_encoder.transform(pred['store'], pred['weekly_sales'])
            pred['dept_enc'] = self.target_encoder.fit_transform(pred['dept'], pred['weekly_sales'])
            X_pred = pred.drop(["weekly_sales"], axis=1)
            y_pred = pred[['weekly_sales']]        
            

        
        
        
        
        
        
    
    
    def process(self):
        
        df = self.load_data()
        df = self.add_date_features(df)
        
        return df

In [72]:
self = SalesPredict()

In [73]:
df = self.process()

(536634, 16)

In [74]:
df

,store,dept,date,weekly_sales,isholiday,temperature,fuel_price,markdown1,markdown2,markdown3,markdown4,markdown5,cpi,unemployment,type,size,month,dayofyear,week_no,week_num
0,1,1,2010-02-05,24924.50,0,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,A,151315,2,36,5,1
1,1,1,2010-02-12,46039.49,1,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,A,151315,2,43,6,2
2,1,1,2010-02-19,41595.55,0,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,A,151315,2,50,7,3
3,1,1,2010-02-26,19403.54,0,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,A,151315,2,57,8,4
4,1,1,2010-03-05,21827.90,0,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,A,151315,3,64,9,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536629,45,98,2013-06-28,NaN,0,76.05,3.639,4842.29,975.03,3.00,2449.97,3169.69,NaN,NaN,B,118221,6,179,26,5
536630,45,98,2013-07-05,NaN,0,77.50,3.614,9090.48,2268.58,582.74,5797.47,1514.93,NaN,NaN,B,118221,7,186,27,1
536631,45,98,2013-07-12,NaN,0,79.37,3.614,3789.94,1827.31,85.72,744.84,2150.36,NaN,NaN,B,118221,7,193,28,2
536632,45,98,2013-07-19,NaN,0,82.84,3.737,2961.49,1047.07,204.19,363.00,1059.46,NaN,NaN,B,118221,7,200,29,3
536633,45,98,2013-07-26,NaN,0,76.06,3.804,212.02,851.73,2.06,10.88,1864.57,NaN,NaN,B,118221,7,207,30,4

In [70]:
df.dayofweek.value_counts()

Friday    536634
Name: dayofweek, dtype: int64

In [76]:
train.tail(100)

        store  dept        date  weekly_sales  isholiday
421470     45    98  2010-12-03        349.38      False
421471     45    98  2010-12-10        665.96      False
421472     45    98  2010-12-17        222.48      False
421473     45    98  2010-12-24        222.48      False
421474     45    98  2010-12-31         74.55       True
421475     45    98  2011-01-07        122.50      False
421476     45    98  2011-01-14         42.00      False
421477     45    98  2011-01-21          2.00      False
421478     45    98  2011-01-28         77.00      False
421479     45    98  2011-02-04         57.25      False
421480     45    98  2011-02-11        388.80       True
421481     45    98  2011-02-18        284.50      False
421482     45    98  2011-02-25        675.26      False
421483     45    98  2011-03-04       1218.64      False
421484     45    98  2011-03-11       1071.41      False
421485     45    98  2011-03-18        693.82      False
421486     45    98  2011-03-25       1101.26      False
421487     45    98  2011-04-01        991.32      False
421488     45    98  2011-04-08       1301.43      False
421489     45    98  2011-04-15        980.06      False
421490     45    98  2011-04-22       1058.62      False
421491     45    98  2011-04-29        868.74      False
421492     45    98  2011-05-06        669.07      False
421493     45    98  2011-05-13        770.47      False
421494     45    98  2011-05-20        846.44      False
421495     45    98  2011-05-27       1369.21      False
421496     45    98  2011-06-03       1504.71      False
421497     45    98  2011-06-10        991.60      False
421498     45    98  2011-06-17       1086.62      False
421499     45    98  2011-06-24        737.36      False
421500     45    98  2011-07-01       1005.98      False
421501     45    98  2011-07-08       1021.94      False
421502     45    98  2011-07-15       1033.14      False
421503     45    98  2011-07-22        614.73      False
421504     45    98  2011-07-29        599.03      False
421505     45    98  2011-08-05        982.60      False
421506     45    98  2011-08-12        827.40      False
421507     45    98  2011-08-19        535.68      False
421508     45    98  2011-08-26        385.96      False
421509     45    98  2011-09-02        601.42      False
421510     45    98  2011-09-09       1092.66       True
421511     45    98  2011-09-16        791.96      False
421512     45    98  2011-09-23        655.12      False
421513     45    98  2011-09-30        727.05      False
421514     45    98  2011-10-07        894.98      False
421515     45    98  2011-10-14        996.40      False
421516     45    98  2011-10-21       1058.84      False
421517     45    98  2011-10-28       1167.90      False
421518     45    98  2011-11-04        749.18      False
421519     45    98  2011-11-11        897.22      False
421520     45    98  2011-11-18        503.20      False
421521     45    98  2011-11-25        794.62       True
421522     45    98  2011-12-02        538.51      False
421523     45    98  2011-12-09        572.72      False
421524     45    98  2011-12-16        853.46      False
421525     45    98  2011-12-23       1084.78      False
421526     45    98  2011-12-30        553.21       True
421527     45    98  2012-01-06        698.76      False
421528     45    98  2012-01-13        677.71      False
421529     45    98  2012-01-20        848.84      False
421530     45    98  2012-01-27        671.40      False
421531     45    98  2012-02-03        772.51      False
421532     45    98  2012-02-10        770.86       True
421533     45    98  2012-02-17        889.98      False
421534     45    98  2012-02-24        544.34      False
421535     45    98  2012-03-02        654.52      False
421536     45    98  2012-03-09        871.34      False
421537     45    98  2012-03-16        747.50      False
421538     45    98  2012-03-23        550.98      False
421539     45    98  2012-03-30        763.60      False
421540     45    98  2012-04-06        778.70      False
421541     45    98  2012-04-13        559.14      False
421542     45    98  2012-04-20        605.80      False
421543     45    98  2012-04-27        619.41      False
421544     45    98  2012-05-04        694.25      False
421545     45    98  2012-05-11        893.60      False
421546     45    98  2012-05-18        745.44      False
421547     45    98  2012-05-25        795.94      False
421548     45    98  2012-06-01        874.64      False
421549     45    98  2012-06-08        713.50      False
421550     45    98  2012-06-15        856.35      False
421551     45    98  2012-06-22        622.62      False
421552     45    98  2012-06-29        690.52      False
421553     45    98  2012-07-06        659.65      False
421554     45    98  2012-07-13        695.21      False
421555     45    98  2012-07-20        845.30      False
421556     45    98  2012-07-27        657.63      False
421557     45    98  2012-08-03        516.46      False
421558     45    98  2012-08-10        727.49      False
421559     45    98  2012-08-17        500.16      False
421560     45    98  2012-08-24        415.40      False
421561     45    98  2012-08-31        346.04      False
421562     45    98  2012-09-07        352.44       True
421563     45    98  2012-09-14        605.96      False
421564     45    98  2012-09-21        467.30      False
421565     45    98  2012-09-28        508.37      False
421566     45    98  2012-10-05        628.10      False
421567     45    98  2012-10-12       1061.02      False
421568     45    98  2012-10-19        760.01      False
421569     45    98  2012-10-26       1076.80      False